### PR TITLE
Replace enb-diverse-js to enb-js

### PR DESCRIPTION
**Pull request by Realetive**

### CODE REVIEW

**Comment by blond** [comment]
@Realetive thank you for PR.

You can use `includeYM` option in `browser-js` tech instead of `prepend-modules` tech from `enb-modules` package.

See [example](https://github.com/bem/project-stub/commit/b8ddf74f5d16fc2e2d9fc68bc07e210626fff3e9) in `project-stub`.

@eGavr could you help realize this?

**Comment by eGavr** [comment]
@blond 
Создай issue + задачу.

Непосредственно по этому PR  есть замечания?

**Comment by blond** [comment]
issue — https://github.com/bem/generator-bem-stub/issues/145

По PR других замечаний нет.

**Comment by eGavr** [comment]
Тогда вливаю?

**Comment by blond** [comment]
:fire:

**Pull request merged**
