### PR TITLE
Update 'bem-components' to v2.0.0; update deps

### LINKED ISSUE #101: Do we need bem-core in deps if we have bem-components?
Just because bem-components knows more about the needed version of bem-core.

### PR DESCRIPTION
**Pull request by eGavr**
closes #101

### CODE REVIEW

**Comment by eGavr** [comment]
После того как вольем буду выпускать `generator-bem-stub@v0.3.0`

**Comment by zxqfox** [comment]
:+1: Thanks!

p.s. Missing tests ;-(

**Comment by eGavr** [comment]
There are specific testing system for yeoman generator.
All in all,  func testing - is not trivial task, because of the dependencies which generator uses.
So... nowadays only unit testing was provided.

**Comment by zxqfox** [comment]
Nice to know, thanks! ;-)

**Pull request merged**
