### PR TITLE
Feature/tabbed code base

### PR DESCRIPTION
**Pull request by zxqfox**
Rel #103

### CODE REVIEW

**Comment by eGavr** [comment]
Thanks :+1:

**Comment by eGavr** [comment]
It seems that the file [.editorconfig](https://github.com/bem/generator-bem-stub/blob/master/.editorconfig) which is situated in the core of the project in unnecessary, isn't it?

**Comment by tadatuta** [comment]
@eGavr it's unnecessary but still useful ;)

**Comment by eGavr** [comment]
Sounds as contradictory statement )

**Comment by zxqfox** [comment]
Root `.editorconfig` is used for `test/**`, `package.json`, etc., while in `app/.editorconfig` I've described styles for templates except config and lib.

Probably it was a bad idea and we can merge them. ;-\

**Pull request merged**
